name: Seed Generation

on:
  repository_dispatch:
    types: generate_seed-*

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ID: ${{ github.event.client_payload.id }}
      POST_BODY: ${{ github.event.client_payload.post_body }}
    steps:
      - uses: actions/checkout@v3
        if: github.event.client_payload.branch == 'dev'
        with:
          repository: 2dos/DK64-Randomizer-Dev

      - name: Print JSON
        if: github.event.client_payload.branch == 'dev'
        run: echo $POST_BODY

      - uses: actions/checkout@v3
        if: github.event.client_payload.branch != 'dev'
        with:
          repository: 2dos/DK64-Randomizer-Release

      - run: pip install -r requirements-dev.txt

      - name: run build
        run: python3 cli.py --output out.lanky
  
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: log
          path: error.log

      - uses: actions/upload-artifact@v3
        with:
          name: lanky
          path: out.lanky
